/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Achievement {
  categoryId: Generated<string>;
  count: Generated<string>;
  description1: string | null;
  description10: string | null;
  description11: string | null;
  description12: string | null;
  description13: string | null;
  description14: string | null;
  description15: string | null;
  description16: string | null;
  description2: string | null;
  description3: string | null;
  description4: string | null;
  description5: string | null;
  description6: string | null;
  description7: string | null;
  description8: string | null;
  description9: string | null;
  descriptionFlags: Generated<string>;
  flags: Generated<string>;
  icon: Generated<string>;
  ID: Generated<string>;
  mapId: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
  orderInCategory: Generated<string>;
  parentAchievement: Generated<string>;
  points: Generated<string>;
  refAchievement: Generated<string>;
  requiredFaction: Generated<string>;
  titleReward1: string | null;
  titleReward10: string | null;
  titleReward11: string | null;
  titleReward12: string | null;
  titleReward13: string | null;
  titleReward14: string | null;
  titleReward15: string | null;
  titleReward16: string | null;
  titleReward2: string | null;
  titleReward3: string | null;
  titleReward4: string | null;
  titleReward5: string | null;
  titleReward6: string | null;
  titleReward7: string | null;
  titleReward8: string | null;
  titleReward9: string | null;
  titleRewardFlags: Generated<string>;
}

export interface AchievementCategory {
  ID: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
  parentCategory: Generated<string>;
  sortOrder: Generated<string>;
}

export interface AchievementCriteria {
  assetCount: Generated<string>;
  assetType: Generated<string>;
  failAsset: Generated<string>;
  failEvent: Generated<string>;
  flags: Generated<string>;
  ID: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
  referredAchievement: Generated<string>;
  requiredType: Generated<string>;
  showOrder: Generated<string>;
  startAsset: Generated<string>;
  startEvent: Generated<string>;
  timedType: Generated<string>;
  timeLimit: Generated<string>;
  timerStartEvent: Generated<string>;
}

export interface Animationdata {
  BehaviourID: Generated<string>;
  BehaviourTier: Generated<string>;
  BodyFlags: Generated<string>;
  FallbackAnimationID: Generated<string>;
  Flags: Generated<string>;
  ID: Generated<string>;
  Name: string | null;
  WeaponFlags: Generated<string>;
}

export interface Areagroup {
  AreaId1: Generated<string>;
  AreaId2: Generated<string>;
  AreaId3: Generated<string>;
  AreaId4: Generated<string>;
  AreaId5: Generated<string>;
  AreaId6: Generated<string>;
  ID: Generated<string>;
  NextGroup: Generated<string>;
}

export interface Areatable {
  AmbientMultiplier: Generated<number>;
  area_level: Generated<string>;
  exploreFlag: Generated<string>;
  FactionGroup: Generated<string>;
  Flags: Generated<string>;
  ID: Generated<string>;
  Light: Generated<string>;
  LiquidType1: Generated<string>;
  LiquidType2: Generated<string>;
  LiquidType3: Generated<string>;
  LiquidType4: Generated<string>;
  Map: Generated<string>;
  MinElevation: Generated<number>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlag: Generated<string>;
  SoundAmbience: Generated<string>;
  SoundPreferences: Generated<string>;
  SoundPreferencesUnderwater: Generated<string>;
  zone: Generated<string>;
  zoneIntroMusic: Generated<string>;
  ZoneMusic: Generated<string>;
}

export interface Areatrigger {
  Box_Height: Generated<number>;
  Box_Length: Generated<number>;
  Box_Width: Generated<number>;
  Box_Yaw: Generated<number>;
  ContinentID: Generated<string>;
  ID: Generated<string>;
  Radius: Generated<number>;
  X: Generated<number>;
  Y: Generated<number>;
  Z: Generated<number>;
}

export interface Charstartoutfit {
  class: Generated<string>;
  displayInfo1: Generated<string>;
  displayInfo10: Generated<string>;
  displayInfo11: Generated<string>;
  displayInfo12: Generated<string>;
  displayInfo13: Generated<string>;
  displayInfo14: Generated<string>;
  displayInfo15: Generated<string>;
  displayInfo16: Generated<string>;
  displayInfo17: Generated<string>;
  displayInfo18: Generated<string>;
  displayInfo19: Generated<string>;
  displayInfo2: Generated<string>;
  displayInfo20: Generated<string>;
  displayInfo21: Generated<string>;
  displayInfo22: Generated<string>;
  displayInfo23: Generated<string>;
  displayInfo24: Generated<string>;
  displayInfo3: Generated<string>;
  displayInfo4: Generated<string>;
  displayInfo5: Generated<string>;
  displayInfo6: Generated<string>;
  displayInfo7: Generated<string>;
  displayInfo8: Generated<string>;
  displayInfo9: Generated<string>;
  gender: Generated<string>;
  ID: Generated<string>;
  invType1: Generated<string>;
  invType10: Generated<string>;
  invType11: Generated<string>;
  invType12: Generated<string>;
  invType13: Generated<string>;
  invType14: Generated<string>;
  invType15: Generated<string>;
  invType16: Generated<string>;
  invType17: Generated<string>;
  invType18: Generated<string>;
  invType19: Generated<string>;
  invType2: Generated<string>;
  invType20: Generated<string>;
  invType21: Generated<string>;
  invType22: Generated<string>;
  invType23: Generated<string>;
  invType24: Generated<string>;
  invType3: Generated<string>;
  invType4: Generated<string>;
  invType5: Generated<string>;
  invType6: Generated<string>;
  invType7: Generated<string>;
  invType8: Generated<string>;
  invType9: Generated<string>;
  itemId1: Generated<string>;
  itemId10: Generated<string>;
  itemId11: Generated<string>;
  itemId12: Generated<string>;
  itemId13: Generated<string>;
  itemId14: Generated<string>;
  itemId15: Generated<string>;
  itemId16: Generated<string>;
  itemId17: Generated<string>;
  itemId18: Generated<string>;
  itemId19: Generated<string>;
  itemId2: Generated<string>;
  itemId20: Generated<string>;
  itemId21: Generated<string>;
  itemId22: Generated<string>;
  itemId23: Generated<string>;
  itemId24: Generated<string>;
  itemId3: Generated<string>;
  itemId4: Generated<string>;
  itemId5: Generated<string>;
  itemId6: Generated<string>;
  itemId7: Generated<string>;
  itemId8: Generated<string>;
  itemId9: Generated<string>;
  outfitId: Generated<string>;
  race: Generated<string>;
}

export interface Chartitles {
  femaleTitle1: string | null;
  femaleTitle10: string | null;
  femaleTitle11: string | null;
  femaleTitle12: string | null;
  femaleTitle13: string | null;
  femaleTitle14: string | null;
  femaleTitle15: string | null;
  femaleTitle16: string | null;
  femaleTitle2: string | null;
  femaleTitle3: string | null;
  femaleTitle4: string | null;
  femaleTitle5: string | null;
  femaleTitle6: string | null;
  femaleTitle7: string | null;
  femaleTitle8: string | null;
  femaleTitle9: string | null;
  femaleTitleFlags: Generated<string>;
  ID: Generated<string>;
  maleTitle1: string | null;
  maleTitle10: string | null;
  maleTitle11: string | null;
  maleTitle12: string | null;
  maleTitle13: string | null;
  maleTitle14: string | null;
  maleTitle15: string | null;
  maleTitle16: string | null;
  maleTitle2: string | null;
  maleTitle3: string | null;
  maleTitle4: string | null;
  maleTitle5: string | null;
  maleTitle6: string | null;
  maleTitle7: string | null;
  maleTitle8: string | null;
  maleTitle9: string | null;
  maleTitleFlags: Generated<string>;
  titleMaskId: Generated<string>;
  unk1: Generated<string>;
}

export interface Chatchannels {
  factionGroup: Generated<string>;
  flags: Generated<string>;
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlag: Generated<string>;
  ShortName1: string | null;
  ShortName10: string | null;
  ShortName11: string | null;
  ShortName12: string | null;
  ShortName13: string | null;
  ShortName14: string | null;
  ShortName15: string | null;
  ShortName16: string | null;
  ShortName2: string | null;
  ShortName3: string | null;
  ShortName4: string | null;
  ShortName5: string | null;
  ShortName6: string | null;
  ShortName7: string | null;
  ShortName8: string | null;
  ShortName9: string | null;
  ShortNameFlag: Generated<string>;
}

export interface Chrclasses {
  CinematicSequenceId: Generated<string>;
  DisplayPower: Generated<string>;
  Field01: Generated<string>;
  FileName: string | null;
  Flags: Generated<string>;
  Id: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFemale1: string | null;
  NameFemale10: string | null;
  NameFemale11: string | null;
  NameFemale12: string | null;
  NameFemale13: string | null;
  NameFemale14: string | null;
  NameFemale15: string | null;
  NameFemale16: string | null;
  NameFemale2: string | null;
  NameFemale3: string | null;
  NameFemale4: string | null;
  NameFemale5: string | null;
  NameFemale6: string | null;
  NameFemale7: string | null;
  NameFemale8: string | null;
  NameFemale9: string | null;
  NameFemaleFlags: Generated<string>;
  NameFlags: Generated<string>;
  NameMale1: string | null;
  NameMale10: string | null;
  NameMale11: string | null;
  NameMale12: string | null;
  NameMale13: string | null;
  NameMale14: string | null;
  NameMale15: string | null;
  NameMale16: string | null;
  NameMale2: string | null;
  NameMale3: string | null;
  NameMale4: string | null;
  NameMale5: string | null;
  NameMale6: string | null;
  NameMale7: string | null;
  NameMale8: string | null;
  NameMale9: string | null;
  NameMaleFlags: Generated<string>;
  PetNameToken: Generated<string>;
  RequiredExpansion: Generated<string>;
  SpellClassSet: Generated<string>;
}

export interface Chrraces {
  Alliance: Generated<string>;
  BaseLanguage: Generated<string>;
  CinematicSequenceId: Generated<string>;
  ClientFileString: string | null;
  ClientPrefix: string | null;
  CreatureType: Generated<string>;
  ExploreationSoundId: Generated<string>;
  FacialHairCustom1: string | null;
  FacialHairCustom2: string | null;
  FactionId: Generated<string>;
  FemaleDisplayId: Generated<string>;
  Flags: Generated<string>;
  HairCustomisation: string | null;
  Id: Generated<string>;
  MaleDisplayId: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFemale1: string | null;
  NameFemale10: string | null;
  NameFemale11: string | null;
  NameFemale12: string | null;
  NameFemale13: string | null;
  NameFemale14: string | null;
  NameFemale15: string | null;
  NameFemale16: string | null;
  NameFemale2: string | null;
  NameFemale3: string | null;
  NameFemale4: string | null;
  NameFemale5: string | null;
  NameFemale6: string | null;
  NameFemale7: string | null;
  NameFemale8: string | null;
  NameFemale9: string | null;
  NameFemaleFlags: Generated<string>;
  NameFlags: Generated<string>;
  NameMale1: string | null;
  NameMale10: string | null;
  NameMale11: string | null;
  NameMale12: string | null;
  NameMale13: string | null;
  NameMale14: string | null;
  NameMale15: string | null;
  NameMale16: string | null;
  NameMale2: string | null;
  NameMale3: string | null;
  NameMale4: string | null;
  NameMale5: string | null;
  NameMale6: string | null;
  NameMale7: string | null;
  NameMale8: string | null;
  NameMale9: string | null;
  NameMaleFlags: Generated<string>;
  RequiredExpansion: Generated<string>;
  ResSicknessSpellId: Generated<string>;
  SpalshSoundId: Generated<string>;
}

export interface Cinematiccamera {
  FilePath: string | null;
  ID: Generated<string>;
  O: Generated<number>;
  Voiceover: Generated<string>;
  X: Generated<number>;
  Y: Generated<number>;
  Z: Generated<number>;
}

export interface Cinematicsequences {
  Camera1: Generated<string>;
  Camera2: Generated<string>;
  Camera3: Generated<string>;
  Camera4: Generated<string>;
  Camera5: Generated<string>;
  Camera6: Generated<string>;
  Camera7: Generated<string>;
  Camera8: Generated<string>;
  ID: Generated<string>;
  SoundID: Generated<string>;
}

export interface Creaturedisplayinfo {
  BloodID: Generated<string>;
  BloodLevel: Generated<string>;
  CreatureGeosetData: Generated<string>;
  CreatureModelAlpha: Generated<string>;
  CreatureModelScale: Generated<number>;
  ExtendedDisplayInfoID: Generated<string>;
  ID: Generated<string>;
  ModelID: Generated<string>;
  NPCSoundID: Generated<string>;
  ObjectEffectPackageID: Generated<string>;
  ParticleColorID: Generated<string>;
  PortraitTextureName: string | null;
  SoundID: Generated<string>;
  TextureVariation_1: string | null;
  TextureVariation_2: string | null;
  TextureVariation_3: string | null;
}

export interface Creaturedisplayinfoextra {
  BakedTextureIDblp: string | null;
  BeltDisplayID: Generated<string>;
  BootsDisplayID: Generated<string>;
  BracersDisplayID: Generated<string>;
  CapeDisplayID: Generated<string>;
  ChestDisplayID: Generated<string>;
  DisplayRaceID: Generated<string>;
  DisplaySexID: Generated<string>;
  FaceID: Generated<string>;
  FacialHairID: Generated<string>;
  Flags: Generated<string>;
  GlovesDisplayID: Generated<string>;
  HairColorID: Generated<string>;
  HairStyleID: Generated<string>;
  HeadDisplayID: Generated<string>;
  ID: Generated<string>;
  LegsDisplayID: Generated<string>;
  ShirtDisplayID: Generated<string>;
  ShouldersDisplayID: Generated<string>;
  SkinID: Generated<string>;
  TabardDisplayID: Generated<string>;
}

export interface Creaturemodeldata {
  attachedEffectScale: Generated<number>;
  bloodId: Generated<string>;
  collisionHeight: Generated<number>;
  collisionWidth: Generated<number>;
  deathThudShakeSize: Generated<string>;
  flags: Generated<string>;
  foleyMaterialId: Generated<string>;
  footprintParticleScale: Generated<number>;
  footprintTextureId: Generated<string>;
  footprintTextureLength: Generated<number>;
  footprintTextureWidth: Generated<number>;
  footstepShakeSize: Generated<string>;
  geoBoxMaxX: Generated<number>;
  geoBoxMaxY: Generated<number>;
  geoBoxMaxZ: Generated<number>;
  geoBoxMinX: Generated<number>;
  geoBoxMinY: Generated<number>;
  geoBoxMinZ: Generated<number>;
  id: Generated<string>;
  MissileCollisionPush: Generated<number>;
  MissileCollisionRadius: Generated<number>;
  MissileCollisionRaise: Generated<number>;
  modelPath: string | null;
  modelScale: Generated<number>;
  mountHeight: Generated<number>;
  sizeClass: Generated<string>;
  soundData: Generated<string>;
  worldEffectScale: Generated<number>;
}

export interface Creaturesounddata {
  BirthSoundID: Generated<string>;
  CreatureImpactType: Generated<string>;
  CreatureSoundDataIDPet: Generated<string>;
  CustomAttack1: Generated<string>;
  CustomAttack2: Generated<string>;
  CustomAttack3: Generated<string>;
  CustomAttack4: Generated<string>;
  FidgetDelaySecondsMax: Generated<string>;
  FidgetDelaySecondsMin: Generated<string>;
  ID: Generated<string>;
  LoopSoundID: Generated<string>;
  NPCSoundID: Generated<string>;
  SoundAggroID: Generated<string>;
  SoundAlertID: Generated<string>;
  SoundDeathID: Generated<string>;
  SoundExertionCriticalID: Generated<string>;
  SoundExertionID: Generated<string>;
  SoundFidget1: Generated<string>;
  SoundFidget2: Generated<string>;
  SoundFidget3: Generated<string>;
  SoundFidget4: Generated<string>;
  SoundFidget5: Generated<string>;
  SoundFootstepID: Generated<string>;
  SoundInjuryCriticalID: Generated<string>;
  SoundInjuryCrushingBlowID: Generated<string>;
  SoundInjuryID: Generated<string>;
  SoundJumpEndID: Generated<string>;
  SoundJumpStartID: Generated<string>;
  SoundPetAttackID: Generated<string>;
  SoundPetDismissID: Generated<string>;
  SoundPetOrderID: Generated<string>;
  SoundStandID: Generated<string>;
  SoundStunID: Generated<string>;
  SoundWingFlapID: Generated<string>;
  SoundWingGlideID: Generated<string>;
  SpellCastDirectedSoundID: Generated<string>;
  SubmergedSoundID: Generated<string>;
  SubmergeSoundID: Generated<string>;
}

export interface Creaturetype {
  Flags: Generated<string>;
  ID: Generated<string>;
  LocFlags: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
}

export interface Currencycategory {
  flags: Generated<string>;
  id: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
}

export interface Currencytypes {
  bitIndex: Generated<string>;
  category: Generated<string>;
  id: Generated<string>;
  item: Generated<string>;
}

export interface Dungeonencounter {
  bit: Generated<string>;
  difficulty: Generated<string>;
  iconId: Generated<string>;
  ID: Generated<string>;
  mapId: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
  orderIndex: Generated<string>;
}

export interface Faction {
  Description1: string | null;
  Description10: string | null;
  Description11: string | null;
  Description12: string | null;
  Description13: string | null;
  Description14: string | null;
  Description15: string | null;
  Description16: string | null;
  Description2: string | null;
  Description3: string | null;
  Description4: string | null;
  Description5: string | null;
  Description6: string | null;
  Description7: string | null;
  Description8: string | null;
  Description9: string | null;
  DescriptionFlags: Generated<string>;
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
  ParentFactionCap1: Generated<string>;
  ParentFactionCap2: Generated<string>;
  ParentFactionID: Generated<string>;
  ParentFactionMod1: Generated<number>;
  ParentFactionMod2: Generated<number>;
  ReputationBase1: Generated<string>;
  ReputationBase2: Generated<string>;
  ReputationBase3: Generated<string>;
  ReputationBase4: Generated<string>;
  ReputationClassMask1: Generated<string>;
  ReputationClassMask2: Generated<string>;
  ReputationClassMask3: Generated<string>;
  ReputationClassMask4: Generated<string>;
  ReputationFlags1: Generated<string>;
  ReputationFlags2: Generated<string>;
  ReputationFlags3: Generated<string>;
  ReputationFlags4: Generated<string>;
  ReputationIndex: Generated<string>;
  ReputationRaceMask1: Generated<string>;
  ReputationRaceMask2: Generated<string>;
  ReputationRaceMask3: Generated<string>;
  ReputationRaceMask4: Generated<string>;
}

export interface Factiongroup {
  ID: Generated<string>;
  internalName: string | null;
  MaskID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
}

export interface Factiontemplate {
  Enemies1: Generated<string>;
  Enemies2: Generated<string>;
  Enemies3: Generated<string>;
  Enemies4: Generated<string>;
  EnemyGroup: Generated<string>;
  Faction: Generated<string>;
  FactionGroup: Generated<string>;
  Flags: Generated<string>;
  FriendGroup: Generated<string>;
  Friends1: Generated<string>;
  Friends2: Generated<string>;
  Friends3: Generated<string>;
  Friends4: Generated<string>;
  ID: Generated<string>;
}

export interface Filedata {
  FileName: string | null;
  FilePath: string | null;
  ID: Generated<string>;
}

export interface Gameobjectdisplayinfo {
  GeoBoxMaxX: Generated<number>;
  GeoBoxMaxY: Generated<number>;
  GeoBoxMaxZ: Generated<number>;
  GeoBoxMinX: Generated<number>;
  GeoBoxMinY: Generated<number>;
  GeoBoxMinZ: Generated<number>;
  ID: Generated<string>;
  ModelName: string | null;
  ObjectEffectPackageID: Generated<string>;
  Sound1: Generated<string>;
  Sound10: Generated<string>;
  Sound2: Generated<string>;
  Sound3: Generated<string>;
  Sound4: Generated<string>;
  Sound5: Generated<string>;
  Sound6: Generated<string>;
  Sound7: Generated<string>;
  Sound8: Generated<string>;
  Sound9: Generated<string>;
}

export interface Gametips {
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
}

export interface Gemproperties {
  gemType: Generated<string>;
  ID: Generated<string>;
  maxCount_inv: Generated<string>;
  maxCount_item: Generated<string>;
  SpellItemEnchantmentRef: Generated<string>;
}

export interface Holidaydescriptions {
  description1: string | null;
  description10: string | null;
  description11: string | null;
  description12: string | null;
  description13: string | null;
  description14: string | null;
  description15: string | null;
  description16: string | null;
  description2: string | null;
  description3: string | null;
  description4: string | null;
  description5: string | null;
  description6: string | null;
  description7: string | null;
  description8: string | null;
  description9: string | null;
  descriptionFlags: Generated<string>;
  id: Generated<string>;
}

export interface Holidaynames {
  id: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
}

export interface Holidays {
  calendarFlags1: Generated<string>;
  calendarFlags10: Generated<string>;
  calendarFlags2: Generated<string>;
  calendarFlags3: Generated<string>;
  calendarFlags4: Generated<string>;
  calendarFlags5: Generated<string>;
  calendarFlags6: Generated<string>;
  calendarFlags7: Generated<string>;
  calendarFlags8: Generated<string>;
  calendarFlags9: Generated<string>;
  duration1: Generated<string>;
  duration10: Generated<string>;
  duration2: Generated<string>;
  duration3: Generated<string>;
  duration4: Generated<string>;
  duration5: Generated<string>;
  duration6: Generated<string>;
  duration7: Generated<string>;
  duration8: Generated<string>;
  duration9: Generated<string>;
  eventCalendarDescription: Generated<string>;
  eventCalendarName: Generated<string>;
  eventCalendarOverlay: string | null;
  eventDate1: Generated<string>;
  eventDate10: Generated<string>;
  eventDate11: Generated<string>;
  eventDate12: Generated<string>;
  eventDate13: Generated<string>;
  eventDate14: Generated<string>;
  eventDate15: Generated<string>;
  eventDate16: Generated<string>;
  eventDate17: Generated<string>;
  eventDate18: Generated<string>;
  eventDate19: Generated<string>;
  eventDate2: Generated<string>;
  eventDate20: Generated<string>;
  eventDate21: Generated<string>;
  eventDate22: Generated<string>;
  eventDate23: Generated<string>;
  eventDate24: Generated<string>;
  eventDate25: Generated<string>;
  eventDate26: Generated<string>;
  eventDate3: Generated<string>;
  eventDate4: Generated<string>;
  eventDate5: Generated<string>;
  eventDate6: Generated<string>;
  eventDate7: Generated<string>;
  eventDate8: Generated<string>;
  eventDate9: Generated<string>;
  eventFlags: Generated<string>;
  eventSchedulerType: Generated<string>;
  id: Generated<string>;
  looping: Generated<string>;
  priority: Generated<string>;
  region: Generated<string>;
}

export interface Item {
  InventorySlotID: Generated<string>;
  ItemClass: Generated<string>;
  ItemDisplayInfo: Generated<string>;
  itemID: Generated<string>;
  ItemSubClass: Generated<string>;
  MaterialID: Generated<string>;
  SheathID: Generated<string>;
  sound_override_subclassid: Generated<string>;
}

export interface Itemclass {
  Flags: Generated<string>;
  ID: Generated<string>;
  IsWeapon: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  SecondaryID: Generated<string>;
}

export interface Itemdisplayinfo {
  Flags: Generated<string>;
  FootTexture: string | null;
  GeosetGroup1: Generated<string>;
  GeosetGroup2: Generated<string>;
  GeosetGroup3: Generated<string>;
  GroupSoundIndex: Generated<string>;
  HandsTexture: string | null;
  HelmetGeosetVisual1: Generated<string>;
  HelmetGeosetVisual2: Generated<string>;
  ID: Generated<string>;
  InventoryIcon1: string | null;
  InventoryIcon2: string | null;
  ItemVisual: Generated<string>;
  LeftModel: string | null;
  LeftModelTexture: string | null;
  LowerArmTexture: string | null;
  LowerLegTexture: string | null;
  LowerTorsoTexture: string | null;
  ParticleColorID: Generated<string>;
  RightModel: string | null;
  RightModelTexture: string | null;
  SpellVisualID: Generated<string>;
  UpperArmTexture: string | null;
  UpperLegTexture: string | null;
  UpperTorsoTexture: string | null;
}

export interface Itemextendedcost {
  costArena: Generated<string>;
  costHonour: Generated<string>;
  id: Generated<string>;
  personalRating: Generated<string>;
  purchaseGroup: Generated<string>;
  requiredItem1: Generated<string>;
  requiredItem2: Generated<string>;
  requiredItem3: Generated<string>;
  requiredItem4: Generated<string>;
  requiredItem5: Generated<string>;
  requiredItemCount1: Generated<string>;
  requiredItemCount2: Generated<string>;
  requiredItemCount3: Generated<string>;
  requiredItemCount4: Generated<string>;
  requiredItemCount5: Generated<string>;
  unknown1: Generated<string>;
}

export interface Itemset {
  Flags: Generated<string>;
  ID: Generated<string>;
  ItemId1: Generated<string>;
  ItemId10: Generated<string>;
  ItemId11: Generated<string>;
  ItemId12: Generated<string>;
  ItemId13: Generated<string>;
  ItemId14: Generated<string>;
  ItemId15: Generated<string>;
  ItemId16: Generated<string>;
  ItemId17: Generated<string>;
  ItemId2: Generated<string>;
  ItemId3: Generated<string>;
  ItemId4: Generated<string>;
  ItemId5: Generated<string>;
  ItemId6: Generated<string>;
  ItemId7: Generated<string>;
  ItemId8: Generated<string>;
  ItemId9: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  RequiredSkill: Generated<string>;
  RequiredSkillRank: Generated<string>;
  SetBonus1: Generated<string>;
  SetBonus2: Generated<string>;
  SetBonus3: Generated<string>;
  SetBonus4: Generated<string>;
  SetBonus5: Generated<string>;
  SetBonus6: Generated<string>;
  SetBonus7: Generated<string>;
  SetBonus8: Generated<string>;
  SetBonusThreshold1: Generated<string>;
  SetBonusThreshold2: Generated<string>;
  SetBonusThreshold3: Generated<string>;
  SetBonusThreshold4: Generated<string>;
  SetBonusThreshold5: Generated<string>;
  SetBonusThreshold6: Generated<string>;
  SetBonusThreshold7: Generated<string>;
  SetBonusThreshold8: Generated<string>;
}

export interface Itemsubclass {
  Class: Generated<string>;
  displayFlags: Generated<string>;
  displayName1: string | null;
  displayName10: string | null;
  displayName11: string | null;
  displayName12: string | null;
  displayName13: string | null;
  displayName14: string | null;
  displayName15: string | null;
  displayName16: string | null;
  displayName2: string | null;
  displayName3: string | null;
  displayName4: string | null;
  displayName5: string | null;
  displayName6: string | null;
  displayName7: string | null;
  displayName8: string | null;
  displayName9: string | null;
  displayNameFlag: Generated<string>;
  flags: Generated<string>;
  postrequisiteProficiency: Generated<string>;
  prerequisiteProficiency: Generated<string>;
  subClass: Generated<string>;
  verboseName1: string | null;
  verboseName10: string | null;
  verboseName11: string | null;
  verboseName12: string | null;
  verboseName13: string | null;
  verboseName14: string | null;
  verboseName15: string | null;
  verboseName16: string | null;
  verboseName2: string | null;
  verboseName3: string | null;
  verboseName4: string | null;
  verboseName5: string | null;
  verboseName6: string | null;
  verboseName7: string | null;
  verboseName8: string | null;
  verboseName9: string | null;
  verboseNameFlag: Generated<string>;
  weaponAttackSeq: Generated<string>;
  weaponParrySeq: Generated<string>;
  weaponReadySeq: Generated<string>;
  WeaponSwingSize: Generated<string>;
}

export interface Languages {
  ID: Generated<string>;
  LocFlags: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
}

export interface Lfgdungeongroup {
  id: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
  order: Generated<string>;
  parent: Generated<string>;
  type: Generated<string>;
}

export interface Lfgdungeons {
  difficulty: Generated<string>;
  expansion: Generated<string>;
  faction: Generated<string>;
  flags: Generated<string>;
  groupId: Generated<string>;
  id: Generated<string>;
  mapId: Generated<string>;
  maxLevel: Generated<string>;
  minLevel: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
  orderId: Generated<string>;
  targetLevel: Generated<string>;
  targetLevelMax: Generated<string>;
  targetLevelMin: Generated<string>;
  texture: string | null;
  tooltip1: string | null;
  tooltip10: string | null;
  tooltip11: string | null;
  tooltip12: string | null;
  tooltip13: string | null;
  tooltip14: string | null;
  tooltip15: string | null;
  tooltip16: string | null;
  tooltip2: string | null;
  tooltip3: string | null;
  tooltip4: string | null;
  tooltip5: string | null;
  tooltip6: string | null;
  tooltip7: string | null;
  tooltip8: string | null;
  tooltip9: string | null;
  tooltipFlags: Generated<string>;
  typeId: Generated<string>;
}

export interface Light {
  falloffEnd: Generated<number>;
  falloffStart: Generated<number>;
  ID: Generated<string>;
  mapId: Generated<string>;
  paramsClear: Generated<string>;
  paramsClearUnderwater: Generated<string>;
  paramsDeath: Generated<string>;
  paramsStorm: Generated<string>;
  paramsStormUnderwater: Generated<string>;
  paramsUnk1: Generated<string>;
  paramsUnk2: Generated<string>;
  paramsUnk3: Generated<string>;
  posX: Generated<number>;
  posY: Generated<number>;
  posZ: Generated<number>;
}

export interface Lightfloatband {
  floatValue1: Generated<number>;
  floatValue10: Generated<number>;
  floatValue11: Generated<number>;
  floatValue12: Generated<number>;
  floatValue13: Generated<number>;
  floatValue14: Generated<number>;
  floatValue15: Generated<number>;
  floatValue16: Generated<number>;
  floatValue2: Generated<number>;
  floatValue3: Generated<number>;
  floatValue4: Generated<number>;
  floatValue5: Generated<number>;
  floatValue6: Generated<number>;
  floatValue7: Generated<number>;
  floatValue8: Generated<number>;
  floatValue9: Generated<number>;
  ID: Generated<string>;
  numEntries: Generated<string>;
  timeValue1: Generated<string>;
  timeValue10: Generated<string>;
  timeValue11: Generated<string>;
  timeValue12: Generated<string>;
  timeValue13: Generated<string>;
  timeValue14: Generated<string>;
  timeValue15: Generated<string>;
  timeValue16: Generated<string>;
  timeValue2: Generated<string>;
  timeValue3: Generated<string>;
  timeValue4: Generated<string>;
  timeValue5: Generated<string>;
  timeValue6: Generated<string>;
  timeValue7: Generated<string>;
  timeValue8: Generated<string>;
  timeValue9: Generated<string>;
}

export interface Lightintband {
  colourValue1: Generated<string>;
  colourValue10: Generated<string>;
  colourValue11: Generated<string>;
  colourValue12: Generated<string>;
  colourValue13: Generated<string>;
  colourValue14: Generated<string>;
  colourValue15: Generated<string>;
  colourValue16: Generated<string>;
  colourValue2: Generated<string>;
  colourValue3: Generated<string>;
  colourValue4: Generated<string>;
  colourValue5: Generated<string>;
  colourValue6: Generated<string>;
  colourValue7: Generated<string>;
  colourValue8: Generated<string>;
  colourValue9: Generated<string>;
  ID: Generated<string>;
  numEntries: Generated<string>;
  timeValue1: Generated<string>;
  timeValue10: Generated<string>;
  timeValue11: Generated<string>;
  timeValue12: Generated<string>;
  timeValue13: Generated<string>;
  timeValue14: Generated<string>;
  timeValue15: Generated<string>;
  timeValue16: Generated<string>;
  timeValue2: Generated<string>;
  timeValue3: Generated<string>;
  timeValue4: Generated<string>;
  timeValue5: Generated<string>;
  timeValue6: Generated<string>;
  timeValue7: Generated<string>;
  timeValue8: Generated<string>;
  timeValue9: Generated<string>;
}

export interface Lightparams {
  cloudType: Generated<string>;
  glow: Generated<number>;
  higlightSky: Generated<string>;
  ID: Generated<string>;
  oceanDeepAlpha: Generated<number>;
  oceanShallowAlpha: Generated<number>;
  skyboxId: Generated<string>;
  waterDeepAlpha: Generated<number>;
  waterShallowAlpha: Generated<number>;
}

export interface Lightskybox {
  flags: Generated<string>;
  ID: Generated<string>;
  name: string | null;
}

export interface Loadingscreens {
  FileName: string | null;
  HasWideScreen: Generated<string>;
  ID: Generated<string>;
  Name: string | null;
}

export interface Lock {
  action1: Generated<string>;
  action2: Generated<string>;
  action3: Generated<string>;
  action4: Generated<string>;
  action5: Generated<string>;
  action6: Generated<string>;
  action7: Generated<string>;
  action8: Generated<string>;
  ID: Generated<string>;
  index1: Generated<string>;
  index2: Generated<string>;
  index3: Generated<string>;
  index4: Generated<string>;
  index5: Generated<string>;
  index6: Generated<string>;
  index7: Generated<string>;
  index8: Generated<string>;
  skill1: Generated<string>;
  skill2: Generated<string>;
  skill3: Generated<string>;
  skill4: Generated<string>;
  skill5: Generated<string>;
  skill6: Generated<string>;
  skill7: Generated<string>;
  skill8: Generated<string>;
  type1: Generated<string>;
  type2: Generated<string>;
  type3: Generated<string>;
  type4: Generated<string>;
  type5: Generated<string>;
  type6: Generated<string>;
  type7: Generated<string>;
  type8: Generated<string>;
}

export interface Locktype {
  CursorName: string | null;
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
  ResourceName1: string | null;
  ResourceName10: string | null;
  ResourceName11: string | null;
  ResourceName12: string | null;
  ResourceName13: string | null;
  ResourceName14: string | null;
  ResourceName15: string | null;
  ResourceName16: string | null;
  ResourceName2: string | null;
  ResourceName3: string | null;
  ResourceName4: string | null;
  ResourceName5: string | null;
  ResourceName6: string | null;
  ResourceName7: string | null;
  ResourceName8: string | null;
  ResourceName9: string | null;
  ResourceNameFlags: Generated<string>;
  Verb1: string | null;
  Verb10: string | null;
  Verb11: string | null;
  Verb12: string | null;
  Verb13: string | null;
  Verb14: string | null;
  Verb15: string | null;
  Verb16: string | null;
  Verb2: string | null;
  Verb3: string | null;
  Verb4: string | null;
  Verb5: string | null;
  Verb6: string | null;
  Verb7: string | null;
  Verb8: string | null;
  Verb9: string | null;
  VerbFlags: Generated<string>;
}

export interface Map {
  AreaTableID: Generated<string>;
  CorpseMapID: Generated<string>;
  CorpseX: Generated<number>;
  CorpseY: Generated<number>;
  DirectoryName: string | null;
  ExpansionID: Generated<string>;
  Flags: Generated<string>;
  ID: Generated<string>;
  InstanceType: Generated<string>;
  LoadingScreenID: Generated<string>;
  MapDescription0_Lang_deDE: string | null;
  MapDescription0_Lang_enCN: string | null;
  MapDescription0_Lang_enGB: string | null;
  MapDescription0_Lang_enTW: string | null;
  MapDescription0_Lang_enUS: string | null;
  MapDescription0_Lang_esES: string | null;
  MapDescription0_Lang_esMX: string | null;
  MapDescription0_Lang_frFR: string | null;
  MapDescription0_Lang_itIT: string | null;
  MapDescription0_Lang_koKR: string | null;
  MapDescription0_Lang_Mask: Generated<string>;
  MapDescription0_Lang_ptBR: string | null;
  MapDescription0_Lang_ptPT: string | null;
  MapDescription0_Lang_ruRU: string | null;
  MapDescription0_Lang_Unk: string | null;
  MapDescription0_Lang_zhCN: string | null;
  MapDescription0_Lang_zhTW: string | null;
  MapDescription1_Lang_deDE: string | null;
  MapDescription1_Lang_enCN: string | null;
  MapDescription1_Lang_enGB: string | null;
  MapDescription1_Lang_enTW: string | null;
  MapDescription1_Lang_enUS: string | null;
  MapDescription1_Lang_esES: string | null;
  MapDescription1_Lang_esMX: string | null;
  MapDescription1_Lang_frFR: string | null;
  MapDescription1_Lang_itIT: string | null;
  MapDescription1_Lang_koKR: string | null;
  MapDescription1_Lang_Mask: Generated<string>;
  MapDescription1_Lang_ptBR: string | null;
  MapDescription1_Lang_ptPT: string | null;
  MapDescription1_Lang_ruRU: string | null;
  MapDescription1_Lang_Unk: string | null;
  MapDescription1_Lang_zhCN: string | null;
  MapDescription1_Lang_zhTW: string | null;
  MapName_Lang_deDE: string | null;
  MapName_Lang_enCN: string | null;
  MapName_Lang_enGB: string | null;
  MapName_Lang_enTW: string | null;
  MapName_Lang_enUS: string | null;
  MapName_Lang_esES: string | null;
  MapName_Lang_esMX: string | null;
  MapName_Lang_frFR: string | null;
  MapName_Lang_itIT: string | null;
  MapName_Lang_koKR: string | null;
  MapName_Lang_Mask: Generated<string>;
  MapName_Lang_ptBR: string | null;
  MapName_Lang_ptPT: string | null;
  MapName_Lang_ruRU: string | null;
  MapName_Lang_Unk: string | null;
  MapName_Lang_zhCN: string | null;
  MapName_Lang_zhTW: string | null;
  MaxPlayers: Generated<string>;
  MinimapIconScale: Generated<number>;
  PVP: Generated<string>;
  RaidOffset: Generated<string>;
  TimeOfDayOverride: Generated<string>;
}

export interface Mapdifficulty {
  difficulty: Generated<string>;
  difficultyString: string | null;
  ID: Generated<string>;
  Map: Generated<string>;
  maxPlayers: Generated<string>;
  message1: Generated<string>;
  message10: Generated<string>;
  message11: Generated<string>;
  message12: Generated<string>;
  message13: Generated<string>;
  message14: Generated<string>;
  message15: Generated<string>;
  message16: Generated<string>;
  message2: Generated<string>;
  message3: Generated<string>;
  message4: Generated<string>;
  message5: Generated<string>;
  message6: Generated<string>;
  message7: Generated<string>;
  message8: Generated<string>;
  message9: Generated<string>;
  messageFlags: Generated<string>;
  raidDurationSeconds: Generated<string>;
}

export interface Movie {
  ID: Generated<string>;
  MoviePath: string | null;
  Volume: Generated<string>;
}

export interface Moviefiledata {
  ID: Generated<string>;
  Resolution: Generated<string>;
}

export interface Movievariation {
  FileDataID: Generated<string>;
  ID: Generated<string>;
  MovieID: Generated<string>;
}

export interface Overridespelldata {
  flags: Generated<string>;
  id: Generated<string>;
  spellid1: Generated<string>;
  spellid10: Generated<string>;
  spellid2: Generated<string>;
  spellid3: Generated<string>;
  spellid4: Generated<string>;
  spellid5: Generated<string>;
  spellid6: Generated<string>;
  spellid7: Generated<string>;
  spellid8: Generated<string>;
  spellid9: Generated<string>;
}

export interface Questsort {
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
}

export interface Screeneffect {
  blackWhiteValue: Generated<string>;
  colour: Generated<string>;
  Id: Generated<string>;
  lightId: Generated<string>;
  Name: string | null;
  screenEdgeSize: Generated<string>;
  soundAmbienceID: Generated<string>;
  soundMusicId: Generated<string>;
  type: Generated<string>;
  unknown: Generated<string>;
}

export interface Skillline {
  canLink: Generated<string>;
  category: Generated<string>;
  costId: Generated<string>;
  description1: string | null;
  description10: string | null;
  description11: string | null;
  description12: string | null;
  description13: string | null;
  description14: string | null;
  description15: string | null;
  description16: string | null;
  description2: string | null;
  description3: string | null;
  description4: string | null;
  description5: string | null;
  description6: string | null;
  description7: string | null;
  description8: string | null;
  description9: string | null;
  descriptionFlags: Generated<string>;
  ID: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
  spellIcon: Generated<string>;
  tooltip1: string | null;
  tooltip10: string | null;
  tooltip11: string | null;
  tooltip12: string | null;
  tooltip13: string | null;
  tooltip14: string | null;
  tooltip15: string | null;
  tooltip16: string | null;
  tooltip2: string | null;
  tooltip3: string | null;
  tooltip4: string | null;
  tooltip5: string | null;
  tooltip6: string | null;
  tooltip7: string | null;
  tooltip8: string | null;
  tooltip9: string | null;
  tooltipFlags: Generated<string>;
}

export interface Skilllineability {
  acquireMethod: Generated<string>;
  characterPoints1: Generated<string>;
  characterPoints2: Generated<string>;
  chrClasses: Generated<string>;
  chrRaces: Generated<string>;
  id: Generated<string>;
  requiredSkillValue: Generated<string>;
  skillGreenLevel: Generated<string>;
  skillGreyLevel: Generated<string>;
  skillId: Generated<string>;
  spellId: Generated<string>;
  spellIdParent: Generated<string>;
  unk1: Generated<string>;
  unk2: Generated<string>;
}

export interface Skilllinecategory {
  ID: Generated<string>;
  LocFlags: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  SortIndex: Generated<string>;
}

export interface Skillraceclassinfo {
  ClassMask: Generated<string>;
  Flags: Generated<string>;
  Id: Generated<string>;
  MinLevel: Generated<string>;
  RaceMask: Generated<string>;
  SkillCostIndex: Generated<string>;
  SkillLineDbcRecord: Generated<string>;
  SkillTierId: Generated<string>;
}

export interface Soundentries {
  EAXDef: Generated<string>;
  FilePath: string | null;
  Flags: Generated<string>;
  Freq1: Generated<string>;
  Freq10: Generated<string>;
  Freq2: Generated<string>;
  Freq3: Generated<string>;
  Freq4: Generated<string>;
  Freq5: Generated<string>;
  Freq6: Generated<string>;
  Freq7: Generated<string>;
  Freq8: Generated<string>;
  Freq9: Generated<string>;
  ID: Generated<string>;
  MaxDistance: Generated<number>;
  MinDistance: Generated<number>;
  Name1: string | null;
  Name10: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  SoundEntriesAdvancedID: Generated<string>;
  SoundName: string | null;
  SoundType: Generated<string>;
  Volume: Generated<number>;
}

export interface Spell {
  ActiveIconID: Generated<string>;
  AreaGroupID: Generated<string>;
  Attributes: Generated<string>;
  AttributesEx: Generated<string>;
  AttributesEx2: Generated<string>;
  AttributesEx3: Generated<string>;
  AttributesEx4: Generated<string>;
  AttributesEx5: Generated<string>;
  AttributesEx6: Generated<string>;
  AttributesEx7: Generated<string>;
  AuraInterruptFlags: Generated<string>;
  BaseLevel: Generated<string>;
  CasterAuraSpell: Generated<string>;
  CasterAuraState: Generated<string>;
  CasterAuraStateNot: Generated<string>;
  CastingTimeIndex: Generated<string>;
  Category: Generated<string>;
  CategoryRecoveryTime: Generated<string>;
  ChannelInterruptFlags: Generated<string>;
  DamageClass: Generated<string>;
  Dispel: Generated<string>;
  DurationIndex: Generated<string>;
  Effect1: Generated<string>;
  Effect2: Generated<string>;
  Effect3: Generated<string>;
  EffectAmplitude1: Generated<string>;
  EffectAmplitude2: Generated<string>;
  EffectAmplitude3: Generated<string>;
  EffectApplyAuraName1: Generated<string>;
  EffectApplyAuraName2: Generated<string>;
  EffectApplyAuraName3: Generated<string>;
  EffectBasePoints1: Generated<string>;
  EffectBasePoints2: Generated<string>;
  EffectBasePoints3: Generated<string>;
  EffectBonusMultiplier1: Generated<number>;
  EffectBonusMultiplier2: Generated<number>;
  EffectBonusMultiplier3: Generated<number>;
  EffectChainTarget1: Generated<string>;
  EffectChainTarget2: Generated<string>;
  EffectChainTarget3: Generated<string>;
  EffectDamageMultiplier1: Generated<number>;
  EffectDamageMultiplier2: Generated<number>;
  EffectDamageMultiplier3: Generated<number>;
  EffectDieSides1: Generated<string>;
  EffectDieSides2: Generated<string>;
  EffectDieSides3: Generated<string>;
  EffectImplicitTargetA1: Generated<string>;
  EffectImplicitTargetA2: Generated<string>;
  EffectImplicitTargetA3: Generated<string>;
  EffectImplicitTargetB1: Generated<string>;
  EffectImplicitTargetB2: Generated<string>;
  EffectImplicitTargetB3: Generated<string>;
  EffectItemType1: Generated<string>;
  EffectItemType2: Generated<string>;
  EffectItemType3: Generated<string>;
  EffectMechanic1: Generated<string>;
  EffectMechanic2: Generated<string>;
  EffectMechanic3: Generated<string>;
  EffectMiscValue1: Generated<string>;
  EffectMiscValue2: Generated<string>;
  EffectMiscValue3: Generated<string>;
  EffectMiscValueB1: Generated<string>;
  EffectMiscValueB2: Generated<string>;
  EffectMiscValueB3: Generated<string>;
  EffectMultipleValue1: Generated<number>;
  EffectMultipleValue2: Generated<number>;
  EffectMultipleValue3: Generated<number>;
  EffectPointsPerComboPoint1: Generated<number>;
  EffectPointsPerComboPoint2: Generated<number>;
  EffectPointsPerComboPoint3: Generated<number>;
  EffectRadiusIndex1: Generated<string>;
  EffectRadiusIndex2: Generated<string>;
  EffectRadiusIndex3: Generated<string>;
  EffectRealPointsPerLevel1: Generated<number>;
  EffectRealPointsPerLevel2: Generated<number>;
  EffectRealPointsPerLevel3: Generated<number>;
  EffectSpellClassMaskA1: Generated<string>;
  EffectSpellClassMaskA2: Generated<string>;
  EffectSpellClassMaskA3: Generated<string>;
  EffectSpellClassMaskB1: Generated<string>;
  EffectSpellClassMaskB2: Generated<string>;
  EffectSpellClassMaskB3: Generated<string>;
  EffectSpellClassMaskC1: Generated<string>;
  EffectSpellClassMaskC2: Generated<string>;
  EffectSpellClassMaskC3: Generated<string>;
  EffectTriggerSpell1: Generated<string>;
  EffectTriggerSpell2: Generated<string>;
  EffectTriggerSpell3: Generated<string>;
  EquippedItemClass: Generated<string>;
  EquippedItemInventoryTypeMask: Generated<string>;
  EquippedItemSubClassMask: Generated<string>;
  ExcludeCasterAuraSpell: Generated<string>;
  ExcludeTargetAuraSpell: Generated<string>;
  FacingCasterFlags: Generated<string>;
  ID: Generated<string>;
  InterruptFlags: Generated<string>;
  ManaCost: Generated<string>;
  ManaCostPercentage: Generated<string>;
  ManaCostPerLevel: Generated<string>;
  ManaPerSecond: Generated<string>;
  ManaPerSecondPerLevel: Generated<string>;
  MaximumAffectedTargets: Generated<string>;
  MaximumLevel: Generated<string>;
  MaximumTargetLevel: Generated<string>;
  Mechanic: Generated<string>;
  MinimumFactionId: Generated<string>;
  MinimumReputation: Generated<string>;
  ModalNextSpell: Generated<string>;
  PowerDisplayId: Generated<string>;
  PowerType: Generated<string>;
  PreventionType: Generated<string>;
  ProcChance: Generated<string>;
  ProcCharges: Generated<string>;
  ProcFlags: Generated<string>;
  RangeIndex: Generated<string>;
  Reagent1: Generated<string>;
  Reagent2: Generated<string>;
  Reagent3: Generated<string>;
  Reagent4: Generated<string>;
  Reagent5: Generated<string>;
  Reagent6: Generated<string>;
  Reagent7: Generated<string>;
  Reagent8: Generated<string>;
  ReagentCount1: Generated<string>;
  ReagentCount2: Generated<string>;
  ReagentCount3: Generated<string>;
  ReagentCount4: Generated<string>;
  ReagentCount5: Generated<string>;
  ReagentCount6: Generated<string>;
  ReagentCount7: Generated<string>;
  ReagentCount8: Generated<string>;
  RecoveryTime: Generated<string>;
  RequiredAuraVision: Generated<string>;
  RequiresSpellFocus: Generated<string>;
  RuneCostID: Generated<string>;
  SchoolMask: Generated<string>;
  Speed: Generated<number>;
  SpellDescription0: string | null;
  SpellDescription1: string | null;
  SpellDescription2: string | null;
  SpellDescription3: string | null;
  SpellDescription4: string | null;
  SpellDescription5: string | null;
  SpellDescription6: string | null;
  SpellDescription7: string | null;
  SpellDescription8: string | null;
  SpellDescriptionFlags0: Generated<string>;
  SpellDescriptionFlags1: Generated<string>;
  SpellDescriptionFlags2: Generated<string>;
  SpellDescriptionFlags3: Generated<string>;
  SpellDescriptionFlags4: Generated<string>;
  SpellDescriptionFlags5: Generated<string>;
  SpellDescriptionFlags6: Generated<string>;
  SpellDescriptionFlags7: Generated<string>;
  SpellDescriptionVariableID: Generated<string>;
  SpellDifficultyID: Generated<string>;
  SpellFamilyFlags: Generated<string>;
  SpellFamilyFlags1: Generated<string>;
  SpellFamilyFlags2: Generated<string>;
  SpellFamilyName: Generated<string>;
  SpellIconID: Generated<string>;
  SpellLevel: Generated<string>;
  SpellMissileID: Generated<string>;
  SpellName0: string | null;
  SpellName1: string | null;
  SpellName2: string | null;
  SpellName3: string | null;
  SpellName4: string | null;
  SpellName5: string | null;
  SpellName6: string | null;
  SpellName7: string | null;
  SpellName8: string | null;
  SpellNameFlag0: Generated<string>;
  SpellNameFlag1: Generated<string>;
  SpellNameFlag2: Generated<string>;
  SpellNameFlag3: Generated<string>;
  SpellNameFlag4: Generated<string>;
  SpellNameFlag5: Generated<string>;
  SpellNameFlag6: Generated<string>;
  SpellNameFlag7: Generated<string>;
  SpellPriority: Generated<string>;
  SpellRank0: string | null;
  SpellRank1: string | null;
  SpellRank2: string | null;
  SpellRank3: string | null;
  SpellRank4: string | null;
  SpellRank5: string | null;
  SpellRank6: string | null;
  SpellRank7: string | null;
  SpellRank8: string | null;
  SpellRankFlags0: Generated<string>;
  SpellRankFlags1: Generated<string>;
  SpellRankFlags2: Generated<string>;
  SpellRankFlags3: Generated<string>;
  SpellRankFlags4: Generated<string>;
  SpellRankFlags5: Generated<string>;
  SpellRankFlags6: Generated<string>;
  SpellRankFlags7: Generated<string>;
  SpellToolTip0: string | null;
  SpellToolTip1: string | null;
  SpellToolTip2: string | null;
  SpellToolTip3: string | null;
  SpellToolTip4: string | null;
  SpellToolTip5: string | null;
  SpellToolTip6: string | null;
  SpellToolTip7: string | null;
  SpellToolTip8: string | null;
  SpellToolTipFlags0: Generated<string>;
  SpellToolTipFlags1: Generated<string>;
  SpellToolTipFlags2: Generated<string>;
  SpellToolTipFlags3: Generated<string>;
  SpellToolTipFlags4: Generated<string>;
  SpellToolTipFlags5: Generated<string>;
  SpellToolTipFlags6: Generated<string>;
  SpellToolTipFlags7: Generated<string>;
  SpellVisual1: Generated<string>;
  SpellVisual2: Generated<string>;
  StackAmount: Generated<string>;
  StanceBarOrder: Generated<string>;
  Stances: Generated<string>;
  StancesNot: Generated<string>;
  StartRecoveryCategory: Generated<string>;
  StartRecoveryTime: Generated<string>;
  TargetAuraSpell: Generated<string>;
  TargetAuraState: Generated<string>;
  TargetAuraStateNot: Generated<string>;
  TargetCreatureType: Generated<string>;
  Targets: Generated<string>;
  Totem1: Generated<string>;
  Totem2: Generated<string>;
  TotemCategory1: Generated<string>;
  TotemCategory2: Generated<string>;
  Unknown1: Generated<string>;
  Unknown2: Generated<string>;
}

export interface Spellcasttimes {
  CastingTime: Generated<string>;
  CastingTimePerLevel: Generated<string>;
  ID: Generated<string>;
  MinimumCastingTime: Generated<string>;
}

export interface Spellcategory {
  Flags: Generated<string>;
  ID: Generated<string>;
}

export interface Spellchaineffects {
  alpha: Generated<string>;
  arcHeight: Generated<number>;
  avgSegLen: Generated<number>;
  blendMode: Generated<string>;
  blue: Generated<string>;
  combo: string | null;
  delayBetweenEffects: Generated<number>;
  flags: Generated<string>;
  green: Generated<string>;
  ID: Generated<string>;
  jointCount: Generated<string>;
  jointMoveSpeed: Generated<number>;
  jointOffsetRadius: Generated<number>;
  jointSmoothness: Generated<number>;
  jointsPerMinorJoint: Generated<string>;
  majorJointScale: Generated<number>;
  maxArcAngle: Generated<number>;
  maxArcSpin: Generated<number>;
  maxDurationBetweenJointJumps: Generated<number>;
  maxFlickerOffDuration: Generated<number>;
  maxFlickerOnDuration: Generated<number>;
  maxWaveAngle: Generated<number>;
  maxWaveSpin: Generated<number>;
  minArcAngle: Generated<number>;
  minArcSpin: Generated<number>;
  minDurationBetweenJointJumps: Generated<number>;
  minFlickerOffDuration: Generated<number>;
  minFlickerOnDuration: Generated<number>;
  minorJointScale: Generated<number>;
  minorJointsPerMajorPoint: Generated<string>;
  minWaveAngle: Generated<number>;
  minWaveSpin: Generated<number>;
  noiseScale: Generated<number>;
  pulseFadeLength: Generated<number>;
  pulseOnLength: Generated<number>;
  pulseSpeed: Generated<number>;
  red: Generated<string>;
  renderLayer: Generated<string>;
  segDelay: Generated<string>;
  segDuration: Generated<string>;
  texCoordScale: Generated<number>;
  texture: string | null;
  textureLength: Generated<number>;
  waveFreq: Generated<number>;
  waveHeight: Generated<number>;
  wavePhase: Generated<number>;
  waveSpeed: Generated<number>;
  width: Generated<number>;
}

export interface Spelldescriptionvariables {
  Formula: string | null;
  ID: Generated<string>;
}

export interface Spelldifficulty {
  Difficulties1: Generated<string>;
  Difficulties2: Generated<string>;
  Difficulties3: Generated<string>;
  Difficulties4: Generated<string>;
  ID: Generated<string>;
}

export interface Spelldispeltype {
  Combinations: Generated<string>;
  ID: Generated<string>;
  ImmunityPossible: Generated<string>;
  InternalName: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
}

export interface Spellduration {
  BaseDuration: Generated<string>;
  ID: Generated<string>;
  MaximumDuration: Generated<string>;
  PerLevel: Generated<string>;
}

export interface Spellfocusobject {
  Flags: Generated<string>;
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
}

export interface Spellicon {
  ID: Generated<string>;
  Name: string | null;
}

export interface Spellitemenchantment {
  charges: Generated<string>;
  Flags: Generated<string>;
  ID: Generated<string>;
  ItemCache: Generated<string>;
  ItemVisuals: Generated<string>;
  maxAmount1: Generated<string>;
  maxAmount2: Generated<string>;
  maxAmount3: Generated<string>;
  minAmount1: Generated<string>;
  minAmount2: Generated<string>;
  minAmount3: Generated<string>;
  objectId1: Generated<string>;
  objectId2: Generated<string>;
  objectId3: Generated<string>;
  requiredLevel: Generated<string>;
  SkillLevel: Generated<string>;
  SkillLine: Generated<string>;
  SpellDispelType1: Generated<string>;
  SpellDispelType2: Generated<string>;
  SpellDispelType3: Generated<string>;
  SpellItemEnchantmentCondition: Generated<string>;
  sRefName0: string | null;
  sRefName1: string | null;
  sRefName10: string | null;
  sRefName11: string | null;
  sRefName12: string | null;
  sRefName13: string | null;
  sRefName14: string | null;
  sRefName15: string | null;
  sRefName2: string | null;
  sRefName3: string | null;
  sRefName4: string | null;
  sRefName5: string | null;
  sRefName6: string | null;
  sRefName7: string | null;
  sRefName8: string | null;
  sRefName9: string | null;
  sRefNameFlags: Generated<string>;
}

export interface Spellmechanic {
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
}

export interface Spellmissile {
  collisionRadius: Generated<number>;
  defaultPitchMax: Generated<number>;
  defaultPitchMin: Generated<number>;
  defaultSpeedMax: Generated<number>;
  defaultSpeedMin: Generated<number>;
  flags: Generated<string>;
  gravity: Generated<number>;
  ID: Generated<string>;
  maxDuration: Generated<number>;
  randomizeFacingMax: Generated<number>;
  randomizeFacingMin: Generated<number>;
  randomizePitchMax: Generated<number>;
  randomizePitchMin: Generated<number>;
  randomizeSpeedMax: Generated<number>;
  randomizeSpeedMin: Generated<number>;
}

export interface Spellmissilemotion {
  flags: Generated<string>;
  ID: Generated<string>;
  missileCount: Generated<string>;
  name: string | null;
  script: string | null;
}

export interface Spellradius {
  ID: Generated<string>;
  MaximumRadius: Generated<number>;
  Radius: Generated<number>;
  RadiusPerLevel: Generated<number>;
}

export interface Spellrange {
  ID: Generated<string>;
  MaximumRangeFriend: Generated<number>;
  MaximumRangeHostile: Generated<number>;
  MinimumRangeFriend: Generated<number>;
  MinimumRangeHostile: Generated<number>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
  ShortName1: string | null;
  ShortName10: string | null;
  ShortName11: string | null;
  ShortName12: string | null;
  ShortName13: string | null;
  ShortName14: string | null;
  ShortName15: string | null;
  ShortName16: string | null;
  ShortName2: string | null;
  ShortName3: string | null;
  ShortName4: string | null;
  ShortName5: string | null;
  ShortName6: string | null;
  ShortName7: string | null;
  ShortName8: string | null;
  ShortName9: string | null;
  ShortNameFlags: Generated<string>;
  Type: Generated<string>;
}

export interface Spellrunecost {
  ID: Generated<string>;
  RuneCost1: Generated<string>;
  RuneCost2: Generated<string>;
  RuneCost3: Generated<string>;
  RunePowerGain: Generated<string>;
}

export interface Spellshapeshiftform {
  ActionBar: Generated<string>;
  CombatRoundTime: Generated<string>;
  CreatureType1: Generated<string>;
  CreatureType2: Generated<string>;
  Display1: Generated<string>;
  Display2: Generated<string>;
  Display3: Generated<string>;
  Display4: Generated<string>;
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlag: Generated<string>;
  presetSpellID1: Generated<string>;
  presetSpellID2: Generated<string>;
  presetSpellID3: Generated<string>;
  presetSpellID4: Generated<string>;
  presetSpellID5: Generated<string>;
  presetSpellID6: Generated<string>;
  presetSpellID7: Generated<string>;
  presetSpellID8: Generated<string>;
  SpellIcon: Generated<string>;
}

export interface Spellvisual {
  AnimEventSoundId: Generated<string>;
  CasterImpactKit: Generated<string>;
  CastKit: Generated<string>;
  ChannelKit: Generated<string>;
  Flags: Generated<string>;
  HasMissile: Generated<string>;
  ID: Generated<string>;
  ImpactAreaKit: Generated<string>;
  ImpactKit: Generated<string>;
  InstantAreaKit: Generated<string>;
  MissileAttachment: Generated<string>;
  MissileCastOffsetX: Generated<number>;
  MissileCastOffsetY: Generated<number>;
  MissileCastOffsetZ: Generated<number>;
  MissileDestinationAttachment: Generated<string>;
  MissileFollowApproach: Generated<string>;
  MissileFollowDropSpeed: Generated<string>;
  MissileFollowGroundFlags: Generated<string>;
  MissileFollowGroundHeight: Generated<string>;
  MissileImpactOffsetX: Generated<number>;
  MissileImpactOffsetY: Generated<number>;
  MissileImpactOffsetZ: Generated<number>;
  MissileModel: Generated<string>;
  MissileMotion: Generated<string>;
  MissilePathType: Generated<string>;
  MissileSound: Generated<string>;
  MissileTargetingKit: Generated<string>;
  PersistentAreaKit: Generated<string>;
  PrecastKit: Generated<string>;
  StateDoneKit: Generated<string>;
  StateKit: Generated<string>;
  TargetImpactKit: Generated<string>;
}

export interface Spellvisualeffectname {
  AreaEffectSize: Generated<number>;
  FilePath: string | null;
  ID: Generated<string>;
  MaxAllowedScale: Generated<number>;
  MinAllowedScale: Generated<number>;
  Name: string | null;
  Scale: Generated<number>;
}

export interface Spellvisualkit {
  AnimationId: Generated<string>;
  BaseEffect: Generated<string>;
  BreathEffect: Generated<string>;
  CharParamOne1: Generated<number>;
  CharParamOne2: Generated<number>;
  CharParamOne3: Generated<number>;
  CharParamOne4: Generated<number>;
  CharParamThree1: Generated<number>;
  CharParamThree2: Generated<number>;
  CharParamThree3: Generated<number>;
  CharParamThree4: Generated<number>;
  CharParamTwo1: Generated<number>;
  CharParamTwo2: Generated<number>;
  CharParamTwo3: Generated<number>;
  CharParamTwo4: Generated<number>;
  CharParamZero1: Generated<number>;
  CharParamZero2: Generated<number>;
  CharParamZero3: Generated<number>;
  CharParamZero4: Generated<number>;
  CharProc1: Generated<string>;
  CharProc2: Generated<string>;
  CharProc3: Generated<string>;
  CharProc4: Generated<string>;
  ChestEffect: Generated<string>;
  Flags: Generated<string>;
  HeadEffect: Generated<string>;
  ID: Generated<string>;
  LeftHandEffect: Generated<string>;
  LeftWeaponEffect: Generated<string>;
  RightHandEffect: Generated<string>;
  RightWeaponEffect: Generated<string>;
  ShakeID: Generated<string>;
  SoundID: Generated<string>;
  SpecialEffect1: Generated<string>;
  SpecialEffect2: Generated<string>;
  SpecialEffect3: Generated<string>;
  StartAnimId: Generated<string>;
  WorldEffect: Generated<string>;
}

export interface Spellvisualkitareamodel {
  enumID: Generated<string>;
  ID: Generated<string>;
  Name: string | null;
}

export interface Spellvisualkitmodelattach {
  AttachmentId: Generated<string>;
  ID: Generated<string>;
  OffsetX: Generated<number>;
  OffsetY: Generated<number>;
  OffsetZ: Generated<number>;
  ParentSpellVisualKitId: Generated<string>;
  Pitch: Generated<number>;
  Roll: Generated<number>;
  SpellVisualEffectNameId: Generated<string>;
  Yaw: Generated<number>;
}

export interface Spellvisualprecasttransitions {
  ID: Generated<string>;
  PrecastHoldAnimName: string | null;
  PrecastLoadAnimName: string | null;
}

export interface Stationery {
  flags: Generated<string>;
  id: Generated<string>;
  itemId: Generated<string>;
  texture: string | null;
}

export interface Talent {
  allowForPetFlags1: Generated<string>;
  allowForPetFlags2: Generated<string>;
  columnIndex: Generated<string>;
  flags: Generated<string>;
  id: Generated<string>;
  prereqRank1: Generated<string>;
  prereqRank2: Generated<string>;
  prereqRank3: Generated<string>;
  prereqTalent1: Generated<string>;
  prereqTalent2: Generated<string>;
  prereqTalent3: Generated<string>;
  requiredSpellId: Generated<string>;
  spellRank1: Generated<string>;
  spellRank2: Generated<string>;
  spellRank3: Generated<string>;
  spellRank4: Generated<string>;
  spellRank5: Generated<string>;
  spellRank6: Generated<string>;
  spellRank7: Generated<string>;
  spellRank8: Generated<string>;
  spellRank9: Generated<string>;
  talentTabId: Generated<string>;
  tierId: Generated<string>;
}

export interface Talenttab {
  backgroundFileName: string | null;
  classMask: Generated<string>;
  creatureFamilyCategory: Generated<string>;
  Flags: Generated<string>;
  iconId: Generated<string>;
  id: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  orderIndex: Generated<string>;
  raceMask: Generated<string>;
}

export interface Taxinodes {
  id: Generated<string>;
  map: Generated<string>;
  mount1: Generated<string>;
  mount2: Generated<string>;
  name1: string | null;
  name10: string | null;
  name11: string | null;
  name12: string | null;
  name13: string | null;
  name14: string | null;
  name15: string | null;
  name16: string | null;
  name2: string | null;
  name3: string | null;
  name4: string | null;
  name5: string | null;
  name6: string | null;
  name7: string | null;
  name8: string | null;
  name9: string | null;
  nameFlags: Generated<string>;
  x: Generated<number>;
  y: Generated<number>;
  z: Generated<number>;
}

export interface Taxipath {
  cost: Generated<string>;
  fromTaxiNode: Generated<string>;
  id: Generated<string>;
  toTaxiNode: Generated<string>;
}

export interface Taxipathnode {
  arrivalEventId: Generated<string>;
  delay: Generated<string>;
  departureEventId: Generated<string>;
  flags: Generated<string>;
  id: Generated<string>;
  mapId: Generated<string>;
  nodeIndex: Generated<string>;
  pathId: Generated<string>;
  x: Generated<number>;
  y: Generated<number>;
  z: Generated<number>;
}

export interface Totemcategory {
  CategoryMask: Generated<string>;
  CategoryType: Generated<string>;
  ID: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
}

export interface Vehicle {
  cameraFadeDistScalarMax: Generated<number>;
  cameraFadeDistScalarMin: Generated<number>;
  cameraPitchOffset: Generated<number>;
  cameraYawOffset: Generated<number>;
  facingLimitLeft: Generated<number>;
  facingLimitRight: Generated<number>;
  flags: Generated<string>;
  id: Generated<string>;
  mouseLookOffsetPitch: Generated<number>;
  msslTrgtArcRepeat: Generated<number>;
  msslTrgtArcSpeed: Generated<number>;
  msslTrgtArcTexture: string | null;
  msslTrgtArcWidth: Generated<number>;
  msslTrgtEndOpacity: Generated<number>;
  msslTrgtImpactModel1: string | null;
  msslTrgtImpactModel2: string | null;
  msslTrgtImpactRadius1: Generated<number>;
  msslTrgtImpactRadius2: Generated<number>;
  msslTrgtImpactTexRadius: Generated<number>;
  msslTrgtImpactTexture: string | null;
  msslTrgtMouseLingering: Generated<number>;
  msslTrgtPitchLingering: Generated<number>;
  msslTrgtTurnLingering: Generated<number>;
  pitchMax: Generated<number>;
  pitchMin: Generated<number>;
  pitchSpeed: Generated<number>;
  PowerDisplay1: Generated<string>;
  PowerDisplay2: Generated<string>;
  PowerDisplay3: Generated<string>;
  seatID1: Generated<string>;
  seatID2: Generated<string>;
  seatID3: Generated<string>;
  seatID4: Generated<string>;
  seatID5: Generated<string>;
  seatID6: Generated<string>;
  seatID7: Generated<string>;
  seatID8: Generated<string>;
  turnSpeed: Generated<number>;
  uiLocomotionType: Generated<string>;
  uiSeatIndicatorType: Generated<string>;
}

export interface Vehicleseat {
  attachmentID: Generated<string>;
  attachmentOffsetX: Generated<number>;
  attachmentOffsetY: Generated<number>;
  attachmentOffsetZ: Generated<number>;
  cameraEnteringDelay: Generated<number>;
  cameraEnteringDuration: Generated<number>;
  cameraEnteringZoom: Generated<number>;
  cameraExitingDelay: Generated<number>;
  cameraExitingDuration: Generated<number>;
  cameraFacingChaseRate: Generated<number>;
  cameraOffsetX: Generated<number>;
  cameraOffsetY: Generated<number>;
  cameraOffsetZ: Generated<number>;
  cameraPosChaseRate: Generated<number>;
  cameraSeatZoomMax: Generated<number>;
  cameraSeatZoomMin: Generated<number>;
  enterAnimLoop: Generated<string>;
  enterAnimStart: Generated<string>;
  enterGravity: Generated<number>;
  enterMaxArcHeight: Generated<number>;
  enterMaxDuration: Generated<number>;
  enterMinArcHeight: Generated<number>;
  enterMinDuration: Generated<number>;
  enterPreDelay: Generated<number>;
  enterSpeed: Generated<number>;
  enterUISoundID: Generated<string>;
  exitAnimEnd: Generated<string>;
  exitAnimLoop: Generated<string>;
  exitAnimStart: Generated<string>;
  exitGravity: Generated<number>;
  exitMaxArcHeight: Generated<number>;
  exitMaxDuration: Generated<number>;
  exitMinArcHeight: Generated<number>;
  exitMinDuration: Generated<number>;
  exitPreDelay: Generated<number>;
  exitSpeed: Generated<number>;
  exitUISoundID: Generated<string>;
  flags: Generated<string>;
  flagsB: Generated<string>;
  ID: Generated<string>;
  passengerAttachmentID: Generated<string>;
  passengerPitch: Generated<number>;
  passengerRoll: Generated<number>;
  passengerYaw: Generated<number>;
  rideAnimLoop: Generated<string>;
  rideAnimStart: Generated<string>;
  rideUpperAnimLoop: Generated<string>;
  rideUpperAnimStart: Generated<string>;
  uiSkin: Generated<string>;
  vehicleAbilityDisplay: Generated<string>;
  vehicleEnterAnim: Generated<string>;
  vehicleEnterAnimBone: Generated<string>;
  vehicleEnterAnimDelay: Generated<number>;
  vehicleExitAnim: Generated<string>;
  vehicleExitAnimBone: Generated<string>;
  vehicleExitAnimDelay: Generated<number>;
  vehicleRideAnimLoop: Generated<string>;
  vehicleRideAnimLoopBone: Generated<string>;
}

export interface Wmoareatable {
  ambienceId: Generated<string>;
  areaTableId: Generated<string>;
  flags: Generated<string>;
  id: Generated<string>;
  introSound: Generated<string>;
  Name1: string | null;
  Name10: string | null;
  Name11: string | null;
  Name12: string | null;
  Name13: string | null;
  Name14: string | null;
  Name15: string | null;
  Name16: string | null;
  Name2: string | null;
  Name3: string | null;
  Name4: string | null;
  Name5: string | null;
  Name6: string | null;
  Name7: string | null;
  Name8: string | null;
  Name9: string | null;
  NameFlags: Generated<string>;
  nameSetId: Generated<string>;
  soundProviderPref: Generated<string>;
  soundProviderPrefUnderwater: Generated<string>;
  wmoGroupId: Generated<string>;
  wmoId: Generated<string>;
  zoneMusic: Generated<string>;
}

export interface Worldstateui {
  areaId: Generated<string>;
  dynamicIcon: string | null;
  dynamicTooltip1: string | null;
  dynamicTooltip10: string | null;
  dynamicTooltip11: string | null;
  dynamicTooltip12: string | null;
  dynamicTooltip13: string | null;
  dynamicTooltip14: string | null;
  dynamicTooltip15: string | null;
  dynamicTooltip16: string | null;
  dynamicTooltip2: string | null;
  dynamicTooltip3: string | null;
  dynamicTooltip4: string | null;
  dynamicTooltip5: string | null;
  dynamicTooltip6: string | null;
  dynamicTooltip7: string | null;
  dynamicTooltip8: string | null;
  dynamicTooltip9: string | null;
  dynamicTooltipFlags: Generated<string>;
  extendedUIStateVar: Generated<string>;
  extendedUIStateVarNeutral: Generated<string>;
  extendedUIStateVarUnk1: Generated<string>;
  extendedUIStateVarUnk2: Generated<string>;
  icon: string | null;
  id: Generated<string>;
  mapId: Generated<string>;
  phaseShift: Generated<string>;
  text1: string | null;
  text10: string | null;
  text11: string | null;
  text12: string | null;
  text13: string | null;
  text14: string | null;
  text15: string | null;
  text16: string | null;
  text2: string | null;
  text3: string | null;
  text4: string | null;
  text5: string | null;
  text6: string | null;
  text7: string | null;
  text8: string | null;
  text9: string | null;
  textFlags: Generated<string>;
  tooltip1: string | null;
  tooltip10: string | null;
  tooltip11: string | null;
  tooltip12: string | null;
  tooltip13: string | null;
  tooltip14: string | null;
  tooltip15: string | null;
  tooltip16: string | null;
  tooltip2: string | null;
  tooltip3: string | null;
  tooltip4: string | null;
  tooltip5: string | null;
  tooltip6: string | null;
  tooltip7: string | null;
  tooltip8: string | null;
  tooltip9: string | null;
  tooltipFlags: Generated<string>;
  type: Generated<string>;
  worldState: Generated<string>;
}

export interface Zonemusic {
  dayMusic: Generated<string>;
  id: Generated<string>;
  name: string | null;
  nightMusic: Generated<string>;
  silenceMaxDay: Generated<string>;
  silenceMaxNight: Generated<string>;
  silenceMinDay: Generated<string>;
  silenceMinNight: Generated<string>;
}

export interface DB {
  achievement: Achievement;
  achievement_category: AchievementCategory;
  achievement_criteria: AchievementCriteria;
  animationdata: Animationdata;
  areagroup: Areagroup;
  areatable: Areatable;
  areatrigger: Areatrigger;
  charstartoutfit: Charstartoutfit;
  chartitles: Chartitles;
  chatchannels: Chatchannels;
  chrclasses: Chrclasses;
  chrraces: Chrraces;
  cinematiccamera: Cinematiccamera;
  cinematicsequences: Cinematicsequences;
  creaturedisplayinfo: Creaturedisplayinfo;
  creaturedisplayinfoextra: Creaturedisplayinfoextra;
  creaturemodeldata: Creaturemodeldata;
  creaturesounddata: Creaturesounddata;
  creaturetype: Creaturetype;
  currencycategory: Currencycategory;
  currencytypes: Currencytypes;
  dungeonencounter: Dungeonencounter;
  faction: Faction;
  factiongroup: Factiongroup;
  factiontemplate: Factiontemplate;
  filedata: Filedata;
  gameobjectdisplayinfo: Gameobjectdisplayinfo;
  gametips: Gametips;
  gemproperties: Gemproperties;
  holidaydescriptions: Holidaydescriptions;
  holidaynames: Holidaynames;
  holidays: Holidays;
  item: Item;
  itemclass: Itemclass;
  itemdisplayinfo: Itemdisplayinfo;
  itemextendedcost: Itemextendedcost;
  itemset: Itemset;
  itemsubclass: Itemsubclass;
  languages: Languages;
  lfgdungeongroup: Lfgdungeongroup;
  lfgdungeons: Lfgdungeons;
  light: Light;
  lightfloatband: Lightfloatband;
  lightintband: Lightintband;
  lightparams: Lightparams;
  lightskybox: Lightskybox;
  loadingscreens: Loadingscreens;
  lock: Lock;
  locktype: Locktype;
  map: Map;
  mapdifficulty: Mapdifficulty;
  movie: Movie;
  moviefiledata: Moviefiledata;
  movievariation: Movievariation;
  overridespelldata: Overridespelldata;
  questsort: Questsort;
  screeneffect: Screeneffect;
  skillline: Skillline;
  skilllineability: Skilllineability;
  skilllinecategory: Skilllinecategory;
  skillraceclassinfo: Skillraceclassinfo;
  soundentries: Soundentries;
  spell: Spell;
  spellcasttimes: Spellcasttimes;
  spellcategory: Spellcategory;
  spellchaineffects: Spellchaineffects;
  spelldescriptionvariables: Spelldescriptionvariables;
  spelldifficulty: Spelldifficulty;
  spelldispeltype: Spelldispeltype;
  spellduration: Spellduration;
  spellfocusobject: Spellfocusobject;
  spellicon: Spellicon;
  spellitemenchantment: Spellitemenchantment;
  spellmechanic: Spellmechanic;
  spellmissile: Spellmissile;
  spellmissilemotion: Spellmissilemotion;
  spellradius: Spellradius;
  spellrange: Spellrange;
  spellrunecost: Spellrunecost;
  spellshapeshiftform: Spellshapeshiftform;
  spellvisual: Spellvisual;
  spellvisualeffectname: Spellvisualeffectname;
  spellvisualkit: Spellvisualkit;
  spellvisualkitareamodel: Spellvisualkitareamodel;
  spellvisualkitmodelattach: Spellvisualkitmodelattach;
  spellvisualprecasttransitions: Spellvisualprecasttransitions;
  stationery: Stationery;
  talent: Talent;
  talenttab: Talenttab;
  taxinodes: Taxinodes;
  taxipath: Taxipath;
  taxipathnode: Taxipathnode;
  totemcategory: Totemcategory;
  vehicle: Vehicle;
  vehicleseat: Vehicleseat;
  wmoareatable: Wmoareatable;
  worldstateui: Worldstateui;
  zonemusic: Zonemusic;
}
